### ISSUE TITLE
Increase WCURLTITLE on DLCLEANER_WCREFERENCEDFILE

### ISSUE THREAD

**Issue by eperezg** [wandjini/Dl-Cleaner#3] opened 2017-12-19 09:33 UTC
Caused by: java.sql.BatchUpdateException: ORA-12899: el valor es demasiado grande para la columna "LIFERAY62"."DLCLEANER_WCREFERENCEDFILE"."WCURLTITLE" (real: 120, mÃ¡ximo: 75)

maybe adding a model-hints.xml with this 
<field name="wcUrlTitle" type="String">
          <hint-collection name="TEXTAREA" />
</field>

**Comment by wandjini** [comment] 2017-12-19 10:03
Duplicate of #4 
Ok

**Closed as completed** 2017-12-20 16:22 UTC
